In [1]:
from numpy import array
from numpy import asarray
from numpy import zeros
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Embedding

/home/erh/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [19]:
docs = ['Well done himanshu!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could digvijay have done better.']
# define class labels
labels = array([1,1,1,1,1,0,0,0,0,0])
# prepare tokenizer
t = Tokenizer()
t.fit_on_texts(docs)
vocab_size = len(t.word_index) + 1
print(vocab_size)
# integer encode the documents
encoded_docs = t.texts_to_sequences(docs)
print(encoded_docs)
# pad documents to a max length of 4 words
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

17
[[6, 2, 7], [3, 1], [8, 4], [9, 1], [10], [11], [5, 4], [12, 3], [5, 1], [13, 14, 15, 2, 16]]
[[ 6  2  7  0]
 [ 3  1  0  0]
 [ 8  4  0  0]
 [ 9  1  0  0]
 [10  0  0  0]
 [11  0  0  0]
 [ 5  4  0  0]
 [12  3  0  0]
 [ 5  1  0  0]
 [14 15  2 16]]


In [12]:
# load the whole embedding into memory
embeddings_index = dict()
f = open('./embeddings/glove.6B.100d.txt')
for line in f:
	values = line.split()
	word = values[0]
	coefs = asarray(values[1:], dtype='float32')
	embeddings_index[word] = coefs
f.close()
# print('vector for the %s:' %embeddings_index['the'])
print('Loaded %s word vectors.' % len(embeddings_index))
# create a weight matrix for words in training docs
embedding_matrix = zeros((vocab_size, 100))
for word, i in t.word_index.items():
	embedding_vector = embeddings_index.get(word)
	if embedding_vector is not None:
		embedding_matrix[i] = embedding_vector

Loaded 400000 word vectors.


In [14]:
print(embeddings_index['himanshu'])

[ 0.13941   -0.93446   -1.1699    -0.45358   -0.80969   -0.4697
 -0.4306    -0.10754    0.18795   -0.54211   -0.15869    0.51521
 -0.60895   -0.45044    0.28322    0.13901   -0.18377   -0.6235
  0.081157   0.26575    0.46618    0.18926   -0.09531    0.37706
  0.15525   -0.28393    0.043943   0.53832   -0.31614    0.30335
 -0.12475   -0.53195    0.26536    0.29936   -0.38363   -1.2319
  0.36661    0.0081704 -0.18437   -0.2652     0.64792    0.52518
 -0.65007    0.01841   -0.45358    0.089317  -0.28032    0.35339
 -0.87161   -0.089397   0.27014   -0.37721    0.20029   -0.4886
  0.48372    0.36473   -0.95744    0.19025   -0.9574     0.22165
  0.25551    0.21751    0.51237    0.43257   -0.12989    0.13111
  0.015008   0.34065    0.072318   0.23782   -0.38093    0.38866
 -0.15616   -0.72631    0.1174    -0.015549  -0.079929  -0.31292
 -0.47915   -0.86838    0.75062   -0.53634    0.11207   -0.50418
  0.49805    0.23473   -0.38806   -0.4929    -0.14628    0.56443
  0.49264   -0.015154  -0.014

In [13]:
print(embeddings_index['digvijay'])

[-6.0950e-01 -1.1155e+00  2.8152e-01  5.0814e-01 -3.1374e-01 -9.3150e-01
 -7.0727e-01  4.1357e-01 -3.3395e-01  1.0936e-01 -2.8128e-01  4.8444e-01
 -6.2852e-01  4.8379e-01 -5.1407e-01  1.7102e-01 -2.9693e-01  5.3141e-02
 -5.2709e-01 -3.9502e-01 -4.1282e-01 -1.6546e-01 -2.2641e-01 -1.0160e-01
 -5.4754e-01  2.7468e-01  7.3284e-02  2.7656e-01  5.5873e-01 -2.4545e-01
 -2.1480e-02  1.0476e-01 -1.8919e-01 -5.7671e-01 -2.3631e-02 -1.9370e-01
 -6.3918e-01  1.5371e-01  2.5235e-02  3.8918e-02  4.2876e-01  3.0519e-01
  6.1021e-01  3.8187e-01 -1.7824e-01 -3.9837e-01  8.2345e-01  4.7700e-01
 -6.1068e-01  4.3747e-01 -4.3080e-01 -4.4698e-01 -1.1411e-01 -4.5047e-01
  3.7518e-01  5.6153e-01 -1.4936e-01  1.9613e-01 -5.1872e-02  2.7713e-01
  8.2881e-02 -6.2014e-01  8.2520e-01  4.7665e-01  2.1820e-01  3.3784e-01
  6.9790e-01  4.8402e-02  9.5558e-01  2.1312e-02  1.1956e-02 -1.1321e-01
  2.1801e-01  2.9487e-01 -3.0471e-01  7.9353e-01 -6.0281e-01  6.7348e-01
  3.1860e-01 -2.3025e-01 -4.1566e-01 -3.7357e-01  6

In [15]:
embedding_matrix = zeros((vocab_size, 100))
for word, i in t.word_index.items():
	embedding_vector = embeddings_index.get(word)
	if embedding_vector is not None:
		embedding_matrix[i] = embedding_vector

In [18]:
embedding_matrix.shape

(17, 100)

In [20]:
print(vocab_size)

17


In [21]:
model = Sequential()
e = Embedding(vocab_size, 100, weights=[embedding_matrix], input_length=4, trainable=False)
model.add(e)
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
# summarize the model
print(model.summary())
# fit the model
model.fit(padded_docs, labels, epochs=50, verbose=0)
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 4, 100)            1700      
_________________________________________________________________
flatten_1 (Flatten)          (None, 400)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 401       
Total params: 2,101
Trainable params: 401
Non-trainable params: 1,700
_________________________________________________________________
None
Accuracy: 100.000000


In [40]:
x=array([
[ 6,  2,  7,  0],
[ 3,  1,  0,  0],
[ 8,  4,  0,  0],
[ 9,  1,  0,  0],
[10,  0,  0,  0],
[11,  0,  0,  0],
[ 5,  4,  0,  0],
[12,  3,  0,  0],
[ 5,  1,  0,  0],
[14, 15,  2, 16]])

In [41]:
x.shape

(10, 4)

In [42]:
model.predict(x)

array([[0.8853457 ],
       [0.70829594],
       [0.73753446],
       [0.81827193],
       [0.71885693],
       [0.31836343],
       [0.2573215 ],
       [0.2365119 ],
       [0.31570247],
       [0.05443963]], dtype=float32)